#!/bin/bash

echo "=========================================="
echo "FLUX2 - COMPLETE FIX SCRIPT"
echo "=========================================="
echo ""
echo "This script fixes ALL issues:"
echo "  1. DataInitializer creates users with correct BCrypt hash"
echo "  2. Frontend auth properly maps accessToken -> token"
echo "  3. All services have required dependencies"
echo ""
echo "=========================================="

# Verify we're in Flux2 directory
if [ ! -f "docker-compose.yml" ]; then
    echo "ERROR: Run this from the Flux2 root directory!"
    exit 1
fi

echo ""
echo "All fixes have been applied to this repository!"
echo ""
echo "=========================================="
echo "TO DEPLOY:"
echo "=========================================="
echo ""
echo "1. Stop everything and DELETE volumes (important!):"
echo ""
echo "   docker-compose down -v"
echo ""
echo "2. Rebuild and start:"
echo ""
echo "   docker-compose up --build -d"
echo ""
echo "3. Wait 2-3 minutes, then check logs:"
echo ""
echo "   docker-compose logs -f auth-service"
echo ""
echo "   Look for: 'Default users initialized. Password for all users: Flux@2026'"
echo ""
echo "=========================================="
echo "TEST CREDENTIALS (password: Flux@2026):"
echo "=========================================="
echo ""
echo "  Customer Portal  (http://localhost:3000): ram.bahadur"
echo "  Branch Dashboard (http://localhost:3001): manager.ktm"
echo "  Central Bank     (http://localhost:3002): admin"
echo ""
echo "=========================================="
echo "TROUBLESHOOTING:"
echo "=========================================="
echo ""
echo "If login still fails:"
echo "  1. Check auth-service logs: docker-compose logs auth-service"
echo "  2. Check if users were created: docker-compose logs auth-service | grep 'Created user'"
echo "  3. Check database directly:"
echo "     docker exec -it banking-database psql -U auth_user -d auth_db -c 'SELECT username, role FROM users;'"
echo ""
